name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # a cada 12 horas
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate GitHub snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: Manoel2k67
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Push to the output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate contribution snake"
          add: "output/github-contribution-grid-snake.svg"
